- hosts: localhost
- hosts: live
  vars_files:
    - vars.yml
  roles:
    - role: 01-system-prep
- hosts: chroot
  gather_facts: no
  tasks:
    - name: make sure python is installed in our chroot
      raw: "apt-get update && apt-get -y install python3 python-apt"
- hosts: chroot
  vars_files:
    - vars.yml
  roles:
    - role: 02-chroot
    - role: 03-post-setup
#    - role: 05-post-docker
#    - role: 06-post-kodi
- hosts: chroot
#  vars_files:
#    - vars.yml
  roles:
    - role: 04-netplan-networking 
#    - role: 05-post-docker
#    - role: 06-post-kodi