- hosts: localhost
#- hosts: live
#  vars_files:
#    - vars.yml
#  roles:
#    - role: 01-system-prep
- hosts: chroot
  gather_facts: no
  tasks:
    - name: make sure python is installed in our chroot
      raw: "apt-get update && apt-get -y install python3 python-apt"
- hosts: chroot
  vars_files:
    - vars.yml
  vars_prompt:
    - name: "user_name"
      prompt: "Enter User Name"
      default: "sa"
      private: yes
#      confirm: yes
    - name: "user_password"
      prompt: "Enter User Password"
      default: "sa"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes
    - name: "kodi_name"
      prompt: "Enter Kodi User Name"
      default: "kodi"
      private: yes
#    - name: "disk_name" ## Which disk we are using to create a partition for a logical volume. eg(/dev/sdb,/dev/sdc)
#      prompt: "Disk used for creating partition"
#      default: "sdc"
#      private: no
#    - name: "file_system" ## What type of filesystem it can be ext3, ext4 or xfs etc.
#      prompt: "Type of file system required?"
#      default: "ext4"
#      private: no
#    - name: "mount_point" ## In what name mount point should be created.
#      prompt: "Where need to mount?"
#      default: "mnt/data1500"
#      private: no
  roles:
#    - role: 02-chroot
#    - role: 03-post-setup
    - role: 04-netplan-networking
    - role: 05-environment
    - role: 06-kodi
    - role: 07-services
    - role: 08-samba
#    - role: 07-post-docker
#- hosts: chroot
#  vars_files:
#    - vars.yml
#  roles:
#    - role: 03-post-setup
#    - role: 04-netplan-networking 
#    - role: 05-post-docker
#    - role: 06-post-kodi
