---
- import_tasks: sshd_server.yml
  when: sshd_enabled
- include: users.yml

- apt:
    name: software-properties-common
    state: present

- shell: add-apt-repository universe

- name: Ensure specified packages are in there desired state
  package:
    name: '{{ item }}'
    state: present
  with_flattened: '{{ default_packages }}'
#  tags: [ 'role::kodi:pkgs' ]
#  register: is_softneedinstalled
#  become: yes
  become: true

- name: Create a snapshot of rpool-root file system.
  zfs:
    name: "{{ zfsprep_root_pool }}/root@{{ ansible_date_time.date }}install"
    state: present
# Cleanup
- name: Unmount All Directories
  mount:
    name: "{{ item.name }}"
    state: unmounted
    fstype: none
    src: none
  become: True
  with_items:
   - '/mnt/install/dev'
   - '/mnt/install/proc'
   - '/mnt/install/sys'
   - '/mnt/install/boot/efi'
   - '/mnt/install/boot'
   - '/mnt/install/home'
   - '/mnt/install'
- name: export all zpool
  shell: zpool export -a
