#vars_prompt:
- name: Mount the data1500 filesystem
#  remote_user: ansible
  become: yes
  become_method: sudo
  mount:
    path: "{{ /mnt/data1500 }}" ## Mount point where to mount the FS.
    fstype: ext4
    src: "/dev/sdc" ## Full related path of device mapper to be mounted under mount point.
    opts: rw,noatime,noexec,nodev,nosuid ## Mount options
    state: mounted
- name: Mount the data2000 filesystem
#  remote_user: ansible
  become: yes
  become_method: sudo
  mount:
    path: "{{ /mnt/data2000 }}" ## Mount point where to mount the FS.
    fstype: ext4
    src: "/dev/sdd" ## Full related path of device mapper to be mounted under mount point.
    opts: rw,noatime,noexec,nodev,nosuid ## Mount options
    state: mounted
- name: Mount the data3000 filesystem
#  remote_user: ansible
  become: yes
  become_method: sudo
  mount:
    path: "{{ /mnt/data3000 }}" ## Mount point where to mount the FS.
    fstype: ext4
    src: "/dev/sde" ## Full related path of device mapper to be mounted under mount point.
    opts: rw,noatime,noexec,nodev,nosuid ## Mount options
    state: mounted
