---
#- debug:
#    msg: System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}
#- debug:
#    msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
#- debug:
#    msg: "DISK {{ zfsprep_root_disks }} "
#    msg: "1 {{ zfsprep_root_disks_by_id }} {{ zfsprep_data_disks_by_id  }}"
#zfsprep_target_disks: "{{ zfsprep_legacy_device_nodes | ternary(((zfsprep_root_disks + zfsprep_data_disks) | map('regex_replace', '(.*)', '/dev/\\g<1>') | list),(zfsprep_root_disks_by_id + zfsprep_data_disks_by_id)) }}"
#zfsprep_data_disks: []
#zfsprep_target_disks: "{{ zfsprep_legacy_device_nodes | ternary(((zfsprep_root_disks + zfsprep_data_disks) | map('regex_replace', '(.*)', '/dev/\\g<1>') | list),(zfsprep_root_disks_by_id + zfsprep_data_disks_by_id)) }}"
#- debug:
#    msg: "DISK target {{ zfsprep_target_disks }} "
#    msg: "{{ zfsprep_root_disks | map('extract', hostvars[inventory_hostname]['ansible_devices'], ['links', 'ids', 0]) | list | map('regex_replace', '(.*)', '/dev/disk/by-id/\\g<1>') | list }}"
#     msg: "{{ zfsprep_root_disks | map('extract', hostvars[inventory_hostname]['ansible_devices'], ['links', 'ids', 0]) | list | list }}"
- name: ensure live system has necessary packages installed
  apt:
    name: 
      - mdadm
      - debootstrap
    state: present
    update_cache: true
    cache_valid_time: 3600
#    upgrade: safe
#    update_cache: true
  become: true
  register: apt_out
- debug: var=apt_out
#- debug: var={{ apt_out.stdout.split('\n')[:-1] }}
#  with_items: 
#    - mdadm
#    - debootstrap
#    - gdisk
#    - zfs-initramfs
#    - dkms
#    - dpkg-dev
#    - zfs-dkms
#    - zfsutils-linux
- name: Necessary efi
  apt:
    name:
    state: present
  with_items: 
    - dosfstools
  when: zfsprep_crypt | default(false) | bool == true
- name: forcibly zap disks
  shell: "sgdisk --zap-all {{ item }}"
  with_items:
    - "{{ zfsprep_root_disks_by_id }}"
- name: set up efi disk partitions
  shell: "sgdisk {{ zfsprep_efi_partition_flags }} {{ item }}"
  with_items:
    - "{{ zfsprep_root_device_list }}"
- name: set up boot disk partitions
  shell: "sgdisk {{ zfsprep_boot_partition_flags }} {{ item }}"
  with_items:
    - "{{ zfsprep_root_device_list }}"
- name: set up root disk partitions
  shell: "sgdisk {{ zfsprep_root_partition_flags }} {{ item }}"
  with_items:
    - "{{ zfsprep_root_device_list }}"
- name: print info disk
  shell: "sgdisk --print {{ item }}"
  register: r
  with_items:
    - "{{ zfsprep_root_disks_by_id }}"
- name: debug directory output
  debug:
    msg: "{{r.results|map(attribute='stdout_lines')|list}}"

#- name: check ZFS pool existance
#  command: zpool list -Ho name {{ zfsprep_root_pool }}
#  register: result_pool_list
#  ignore_errors: yes
#  changed_when: false
  
#- name: check ZFS data pool existance
#  command: zpool list -Ho name {{ zfsprep_data_pool }}
#  register: result_datapool_list
#  ignore_errors: yes
#  changed_when: false
#- name: destroy ZFS pool#command: zpool destroy {{ zfs_pool_name }}#when:#- zfs_pool_state | default('present') == 'absent'#- result_pool_list.rc == 0
- name: set up root zfs crypt devices
  shell: "echo -n {{ zfsprep_crypt_passphrase }} | zpool create {{ zfsprep_crypt_flags | join(' ') }} {{ zfsprep_root_pool_opts | join(' ') }} {{ zfsprep_root_pool }} {{ zfsprep_root_pool_type }} {{ zfsprep_root_device_list }}{{ zfsprep_root_part_append }} -f"
  when:
    - zfsprep_crypt | default(false) | bool == true
#    - zfs_pool_state | default('present') == 'present'
#    - result_pool_list.rc == 1  

- name: set up root zfs devices
  shell: "zpool create {{ zfsprep_root_pool_opts | join(' ') }} {{ zfsprep_root_pool }} {{ zfsprep_root_pool_type }} {{ zfsprep_root_device_list }}{{ zfsprep_root_part_append }} -f"
  when:
    - zfsprep_crypt | default(false) | bool != true
#    - zfs_pool_state | default('present') == 'present'
#    - result_pool_list.rc == 1  

- name: create root dataset
  zfs:
    name: "{{ zfsprep_root_pool }}/root"
    state: present
    extra_zfs_properties:
      canmount: noauto
      mountpoint: /
#      canmount: off
#      mountpoint: none
#  when:
#    - zfs_pool_state | default('present') == 'absent'
#    - result_pool_list.rc == 0

- name: manually mount rpool/root before creating other mountpoints
  shell: "zfs mount {{ zfsprep_root_pool }}/root"
  
#- name: create mountpoints in root pool
#  zfs:
#    name: "{{ item.name }}"
#    state: present
#    extra_zfs_properties:
#      "{{ item.properties }}"
#  with_items:
#    - "{{ zfsprep_root_volumes }}"
#- name: chmod 01777 /mnt/var/tmp
#  file:
#    path: /mnt/var/tmp
#    mode: 01777

#- name: set up zfs data devices
#  shell: "zpool create {{ zfsprep_data_pool_opts | join(' ') }} {{ zfsprep_data_pool }} {{ zfsprep_data_pool_type }} {{ zfsprep_data_device_list }}{{ zfsprep_data_part_append }} -f"
#  shell: "zpool create {{ zfsprep_data_pool_opts | join(' ') }} {{ zfsprep_data_pool }} {{ zfsprep_data_pool_type }} {{ map('regex_replace', '(.*)', '/dev/mapper/\\g<1>') | list, (zfsprep_data_partitions | ternary((zfsprep_data_device_list | map('regex_replace', '(.*)', '\\g<1>' + zfsprep_data_part_append) | list), zfsprep_data_device_list)) | join(' ') }}"
#  when: 
#    - zfsprep_data_disks | default(false) | bool == true
#    - zfs_datapool_state | default('present') == 'present'
#    - result_datapool_list.rc == 1  
#- name: create data dataset
#  zfs:
#    name: "{{ zfsprep_data_pool }}/data"
#    state: present
#    extra_zfs_properties:
#      mountpoint: /data
#  when:
#    -  - zfsprep_data_disks | default(false) | bool == true
#- debug: msg: Partition list "{{  zfsprep_root_device_list }}"
- name: format and mount {{ zfsprep_installdir }}boot
  shell: "mke2fs -t ext2 {{ item }} && mkdir {{ zfsprep_installdir }}boot && mount {{ item }} {{ zfsprep_installdir }}boot"
  with_items:
#    - "{{ (zfsprep_root_device_list | length > 1) | (zfsprep_root_device_list | map('regex_replace', '(.*)', '\\g<1>' + zfsprep_boot_part_append) | list).0 }}"
    - "{{ zfsprep_root_device_list }}{{ zfsprep_boot_part_append }}"
  
- name: format and mount {{ zfsprep_installdir }}boot/efi
  shell: "mkfs.msdos -F 32 -n EFI {{ item }} && mkdir {{ zfsprep_installdir }}boot/efi && mount {{ item }} {{ zfsprep_installdir }}boot/efi"
  with_items:
#    - "{{ (zfsprep_root_device_list | length > 1) | (zfsprep_root_device_list | map('regex_replace', '(.*)', '\\g<1>' + zfsprep_efi_part_append) | list).0 }}"
    -  - "{{ zfsprep_root_device_list }}{{ zfsprep_efi_part_append }}"
  when: zfsprep_efi | default(false) | bool == true
  
#- name: create efi mountpoint
#  file:
#    path: {{ zfsprep_installdir }}/boot/efi
#    state: directory
#  when: zfsprep_efi|default(false)|bool == true
  
- name: run debootstrap and set devices=off for root pool
  shell: "debootstrap {{ zfsprep_ubuntu_release }} {{ zfsprep_installdir }} && zfs set devices=off {{ zfsprep_root_pool }}"

#- name: set devices=off for data pool
#  shell: "zfs set devices=off {{ zfsprep_data_pool }}"

- name: write /etc/hostname in chroot
  copy:
    content: "{{ zfsprep_hostname.short }}"
    dest: "{{ zfsprep_installdir }}etc/hostname"
- name: write {{ zfsprep_installdir }}etc/apt/sources.list in chroot
  template:
    src: etc_apt_sources.j2
    dest: "{{ zfsprep_installdir }}etc/apt/sources.list"
- name: add hostname entries to {{ zfsprep_installdir }}hosts in chroot
  lineinfile:
    line: "127.0.0.1 {{ zfsprep_hostname.short }} {{ zfsprep_hostname.long }}"
    path: "{{ zfsprep_installdir }}etc/hosts"
    state: present
    insertbefore: BOF
- name: mount special filesystems for chroot
  shell: "mount --rbind {{ item }}"
  with_items:
    - /dev "{{ zfsprep_installdir }}dev"
    - /proc "{{ zfsprep_installdir }}proc"
    - /sys "{{ zfsprep_installdir }}sys"
  args:
    warn: false
