---
- name: Users | Create Super User
  user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    groups: sudo
    append: yes
    shell: /bin/bash

#- name: Users | Add Super User Authorized Key
#  authorized_key:
#    user: "{{ user_name }}"
#    key: "{{ lookup('file', 'id_rsa.pub') }}"
#    state: present

- name: Users | Enable passwordless sudo
  copy:
    content: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/99-{{ user_name }}"

#- name: Users | Create Super User
#  user:
#    name: "{{ kodi_name }}"
#    groups: kodi, audio, video
#    shell: /sbin/nologin
#    append: yes
#    comment: "Kodi nologin User"
#    state: present
#  become: true
