---
zfsprep_username: sa
zfsprep_userpassword: "$2y$10$1JdBtEi5WePZ7S7LscCvtu26xf/7uVdKywSBDhlEd92TZLun76TnK"  # "vagrant"
packages:
  - gdisk
  - ansible
  - openssh-server
  - mc
  - ssh
  - nano
  - lshw
  - rsync
  - ncdu
  - ethtool
  - wget
  - git
  - gpart
  - gparted 
  - ssh-askpass
  - net-tools
  - tree
  - htop
  - strace 
  - p7zip-full
  - p7zip-rar
