---
packages:
  - gdisk
  - ansible
  - openssh-server
  - mc
  - ssh
  - nano
  - lshw
  - rsync
  - ncdu
  - ethtool
  - wget
  - git
  - gpart
  - gparted 
  - ssh-askpass
  - net-tools
  - tree
  - htop
  - strace 
  - p7zip
  - p7zip-full
  - p7zip-rar
