galaxy_info:
  author: Douglas Atique
  description: A role for network configuration using netplan

  license: MIT

  min_ansible_version: 2.5

  platforms:
  - name: Ubuntu
    versions:
    - bionic

  galaxy_tags: []

dependencies: []
