---
- import_tasks: sshd_server.yml
  when: sshd_enabled
- include: users.yml

- apt:
    name: software-properties-common
    state: present
- shell: add-apt-repository universe
- apt:
    name:
      - gdisk
      - ansible
      - openssh-server
      - mc
      - ssh
      - nano
      - lshw
      - rsync
      - ncdu
      - ethtool
      - wget
      - git
      - gpart
      - gparted
      - ssh-askpass
      - net-tools
      - tree
      - htop
      - strace
      - p7zip
      - p7zip-full
      - p7zip-rar
    state: present
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - "{{ packages }}"
#    register: apt_out

#- debug: var=apt_out
#- debug: var={{ apt_out.stdout.split('\n')[:-1] }}
- name: Create a snapshot of rpool/root file system.
  zfs:
    name: "{{ zfsprep_root_pool }}/root@{{ ansible_date_time.date }}install"
    state: present
 Cleanup
- name: Unmount All Directories
  mount:
    name: "{{ item.name }}"
    state: unmounted
    fstype: none
    src: none
  become: True
  with_items:
   - '/mnt/install/dev'
   - '/mnt/install/proc'
   - '/mnt/install/sys'
   - '/mnt/install/boot/efi'
   - '/mnt/install/boot'
   - '/mnt/install/home'
   - '/mnt/install'
- name: export all zpool
  shell: zpool export -a
