---
- import_tasks: sshd_server.yml
  when: sshd_enabled
- include: users.yml

- apt:
    name: software-properties-common
    state: present
- shell: add-apt-repository universe
- apt:
    name:
      - gdisk
      - ansible
      - openssh-server
      - mc
      - ssh
      - nano
      - lshw
      - rsync
      - ncdu
      - ethtool
      - wget
      - git
      - gpart
      - gparted
      - ssh-askpass
      - net-tools
      - tree
      - htop
      - strace
      - p7zip
      - p7zip-full
      - p7zip-rar
    state: present
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - "{{ packages }}"
#    register: apt_out

#- debug: var=apt_out
#- debug: var={{ apt_out.stdout.split('\n')[:-1] }}
