---
- apt:
    name: software-properties-common
    state: present
- shell: add-apt-repository universe
- apt:
    name:
      - gdisk
      - ansible
      - openssh-server
      - mc
      - ssh
      - nano
      - lshw
      - rsync
      - ncdu
      - ethtool
      - wget
      - git
      - gpart
      - gparted
      - ssh-askpass
      - net-tools
      - tree
      - htop
      - strace
      - p7zip
      - p7zip-full
      - p7zip-rar
    state: present
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - "{{ packages }}"
- name: explicitly write nocompress to /etc/logrotate.conf
  replace:
    path: /etc/logrotate.conf
    regexp: '^.*compress$'
    replace: 'nocompress'
- name: find files in /etc/logrotate.d
  find:
    paths: /etc/logrotate.d
    file_type: file
  register: zfsprep_logrotate_jobs
- name: comment all compress from logrotate.conf
  replace:
    path: "{{ item.path }}"
    regexp: '^(.*compress.*)$'
    replace: '#\1'
  with_items: "{{ zfsprep_logrotate_jobs.files }}"
- name: Create a snapshot of rpool/root file system.
  zfs:
    name: {{ zfsprep_root_pool }}/root@{{ ansible_date_time.date }}install
    state: present
- name umount all
  shell: mount | grep -v zfs | tac | awk '/mnt/ {print $3}' | xargs -i{} umount -lf {}
- name: export all zpool
  shell: zpool export -a